Adds tests for recette-batch
livingdata-co/gpf-geocodeur pull request #6
Opened 2024-10-02 14:40 UTC by GllmR

This pull request adds some tests in recette-batch.

2024-10-03 21:25 UTC, jdesboeufs requested changes

2024-10-03 21:25 UTC, jdesboeufs commented on tests/recette-batch/index.js
> +    catergory: 'mairie'
Typo

2024-10-03 21:25 UTC, jdesboeufs commented on tests/recette-batch/index.js
> +    type: 'mairie'
Type concerne address, aucun impact ici

2024-10-03 21:25 UTC, jdesboeufs commented on tests/recette-batch/index.js
> +    category: 'type'
??

2024-10-03 21:25 UTC, jdesboeufs commented on tests/recette-batch/index.js
> +  }, {indexes: ['poi']})
Il manque `columns: ['q']`

2024-10-03 21:25 UTC, jdesboeufs commented on tests/recette-batch/index.js
> +    columns: ['category']
q

2024-10-03 21:25 UTC, jdesboeufs commented on tests/recette-batch/index.js
> +    columns: ['category'],
q

2024-10-03 21:25 UTC, jdesboeufs commented on tests/recette-batch/index.js
> +test('poi - search - batch', async t => {
Pas utile de faire du batch

2024-10-04 07:41 UTC, GllmR commented on tests/recette-batch/index.js
> +    type: 'mairie'
C'est justement le but du test, c'est dans le titre.

Je fournis une colonne qui n'existe pas, j'obtiens un premier résultat (Cimetière).
Ensuite, je passe la colonne "type" en "category" et j'obtiens un autre résultat (mairie).

2024-10-04 07:44 UTC, GllmR commented on tests/recette-batch/index.js
> +test('poi - search - batch', async t => {
Pourquoi ? 
C'est à cause de ça qu'on n'a pas vu passer le problème sur `parcel`.

2024-10-04 08:34 UTC, jdesboeufs commented on tests/recette-batch/index.js
> +test('poi - search - batch', async t => {
La fonction executeSingleRequest fait déjà ça, on est dans les tests unitaires batch.

2024-10-08 14:42 UTC, merged